name: Robstestsite
favicon: null
layout_spectrum: 0.9199154090601951
typography_spectrum: 0.8069482175633311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1997466527391225
  lightness: 0.8898518441710621
  saturation: 0.7095749862492085
  rhythmicContrast: 0.8481705742888153
purpose: []
